#!/usr/bin/env php
<?php
/*
 * This file is part of the bc-review package.
 *
 * (c) Damien Walsh <me@damow.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use BcReview\Command\ReviewCommand;
use BcReview\Config;

Config::getConfig(__DIR__ . '/config.yml');

$application = new Application();
$application->add(new ReviewCommand());
$application->run();
